services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: ${NODE_ENV}
      PGHOST: db
      PGUSER: ${DB_USERNAME}
      PGPASSWORD: ${DB_PASSWORD}
      PGDATABASE: diolog-db
      PGPORT: 5432
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: diolog-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
