services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      PGHOST: db
      PGUSER: dio-brando
      PGPASSWORD: zawarudo369
      PGDATABASE: diolog-db
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: postgres
    environment:
      POSTGRES_USER: dio-brando
      POSTGRES_PASSWORD: zawarudo369
      POSTGRES_DB: diolog-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network
volumes:
  postgres-data:

networks:
  my-network:
    driver: ipvlan